### ISSUE TITLE
Text is difficult to read on Chrome dark mode

### ISSUE THREAD

**Issue by viglucci** [rsocket/rsocket-chrome-devtools#16]
The text color rendered when Chrome is in dark mode clashes with the background color used by Chrome, rendering the text unreadable.

![image](https://user-images.githubusercontent.com/6305490/132160706-358f82fe-1ace-4c9d-be72-2c87be8cda89.png)

If you highlight the text, you see that it is actually rendering, it's just essentially the same color as the background.

![image](https://user-images.githubusercontent.com/6305490/132160746-a8e97a3e-ef09-493e-b2d8-00380b9f0f96.png)

## Expected Behavior

Text is readable when Chrome is running in dark mode.

## Actual Behavior

The text is unreadable.

## Steps to Reproduce

Install the plugin and enable Chromes dark mode.

**Comment by SerCeMan** [comment]
Hey, @viglucci! Thank you for reporting! I'm not a very good designer, but I added the initial support for dark mode in https://github.com/rsocket/rsocket-chrome-devtools/commit/8176a5e692128f7ffe5fcdc15c7c008fd70585ee. 

<img width="970" alt="Screen Shot 2021-09-08 at 1 03 13 am" src="https://user-images.githubusercontent.com/1780970/132367789-7899c8fa-d464-4d8e-b955-07eb2bf38812.png">

**Comment by viglucci** [comment]
@SerCeMan awesome! Thanks for the quick fix!
